/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module tilesort_2 (
    input clk,
    output reg tile1,
    output reg tile2,
    output reg tile3,
    output reg tile4,
    output reg tile5
  );
  
  
  
  wire [1-1:0] M_tilea_yellow;
  reg [10-1:0] M_tilea_horizontaloffset;
  reg [7-1:0] M_tilea_verticaloffset;
  reg [3-1:0] M_tilea_shape;
  reg [3-1:0] M_tilea_orientation;
  tiledraw_4 tilea (
    .clk(clk),
    .horizontaloffset(M_tilea_horizontaloffset),
    .verticaloffset(M_tilea_verticaloffset),
    .shape(M_tilea_shape),
    .orientation(M_tilea_orientation),
    .yellow(M_tilea_yellow)
  );
  wire [1-1:0] M_tileb_yellow;
  reg [10-1:0] M_tileb_horizontaloffset;
  reg [7-1:0] M_tileb_verticaloffset;
  reg [3-1:0] M_tileb_shape;
  reg [3-1:0] M_tileb_orientation;
  tiledraw_4 tileb (
    .clk(clk),
    .horizontaloffset(M_tileb_horizontaloffset),
    .verticaloffset(M_tileb_verticaloffset),
    .shape(M_tileb_shape),
    .orientation(M_tileb_orientation),
    .yellow(M_tileb_yellow)
  );
  wire [1-1:0] M_tilec_yellow;
  reg [10-1:0] M_tilec_horizontaloffset;
  reg [7-1:0] M_tilec_verticaloffset;
  reg [3-1:0] M_tilec_shape;
  reg [3-1:0] M_tilec_orientation;
  tiledraw_4 tilec (
    .clk(clk),
    .horizontaloffset(M_tilec_horizontaloffset),
    .verticaloffset(M_tilec_verticaloffset),
    .shape(M_tilec_shape),
    .orientation(M_tilec_orientation),
    .yellow(M_tilec_yellow)
  );
  wire [1-1:0] M_tiled_yellow;
  reg [10-1:0] M_tiled_horizontaloffset;
  reg [7-1:0] M_tiled_verticaloffset;
  reg [3-1:0] M_tiled_shape;
  reg [3-1:0] M_tiled_orientation;
  tiledraw_4 tiled (
    .clk(clk),
    .horizontaloffset(M_tiled_horizontaloffset),
    .verticaloffset(M_tiled_verticaloffset),
    .shape(M_tiled_shape),
    .orientation(M_tiled_orientation),
    .yellow(M_tiled_yellow)
  );
  wire [1-1:0] M_tilee_yellow;
  reg [10-1:0] M_tilee_horizontaloffset;
  reg [7-1:0] M_tilee_verticaloffset;
  reg [3-1:0] M_tilee_shape;
  reg [3-1:0] M_tilee_orientation;
  tiledraw_4 tilee (
    .clk(clk),
    .horizontaloffset(M_tilee_horizontaloffset),
    .verticaloffset(M_tilee_verticaloffset),
    .shape(M_tilee_shape),
    .orientation(M_tilee_orientation),
    .yellow(M_tilee_yellow)
  );
  
  always @* begin
    M_tilea_horizontaloffset = 1'h0;
    M_tilea_verticaloffset = 1'h0;
    M_tilea_shape = 1'h0;
    M_tilea_orientation = 1'h0;
    tile1 = M_tilea_yellow;
    M_tileb_horizontaloffset = 7'h78;
    M_tileb_verticaloffset = 1'h0;
    M_tileb_shape = 1'h0;
    M_tileb_orientation = 1'h0;
    tile2 = M_tileb_yellow;
    M_tilec_horizontaloffset = 8'hf0;
    M_tilec_verticaloffset = 1'h0;
    M_tilec_shape = 1'h0;
    M_tilec_orientation = 1'h0;
    tile3 = M_tilec_yellow;
    M_tiled_horizontaloffset = 9'h168;
    M_tiled_verticaloffset = 1'h0;
    M_tiled_shape = 1'h0;
    M_tiled_orientation = 1'h0;
    tile4 = M_tiled_yellow;
    M_tilee_horizontaloffset = 9'h1e0;
    M_tilee_verticaloffset = 1'h0;
    M_tilee_shape = 1'h0;
    M_tilee_orientation = 1'h0;
    tile5 = M_tilee_yellow;
  end
endmodule
