/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module tiledraw_4 (
    input clk,
    input [9:0] horizontaloffset,
    input [6:0] verticaloffset,
    input [2:0] shape,
    input [2:0] orientation,
    output reg yellow
  );
  
  
  
  wire [1-1:0] M_hvsync_vga_h_sync;
  wire [1-1:0] M_hvsync_vga_v_sync;
  wire [1-1:0] M_hvsync_inDisplayArea;
  wire [11-1:0] M_hvsync_CounterX;
  wire [9-1:0] M_hvsync_CounterY;
  hvsync_generator_1 hvsync (
    .clk(clk),
    .vga_h_sync(M_hvsync_vga_h_sync),
    .vga_v_sync(M_hvsync_vga_v_sync),
    .inDisplayArea(M_hvsync_inDisplayArea),
    .CounterX(M_hvsync_CounterX),
    .CounterY(M_hvsync_CounterY)
  );
  wire [51-1:0] M_bram_outdata;
  reg [6-1:0] M_bram_address;
  bram_15 bram (
    .clk(clk),
    .address(M_bram_address),
    .outdata(M_bram_outdata)
  );
  
  reg [10:0] counterh;
  
  reg [8:0] counterv;
  
  reg [50:0] fullcounter;
  
  always @* begin
    counterh = M_hvsync_CounterX;
    counterv = M_hvsync_CounterY;
    if (((counterh >= 9'h177 + horizontaloffset & counterh <= 9'h1dd + horizontaloffset)) & ((counterv >= 7'h78 + verticaloffset) & (counterv <= 8'hb4 + verticaloffset))) begin
      M_bram_address = counterv - verticaloffset - 7'h78;
      fullcounter = M_bram_outdata;
      yellow = fullcounter[(6'h33 - ((counterh - 9'h177 - horizontaloffset) / 2'h2))*1+0-:1];
    end else begin
      M_bram_address = 10'h3e7;
      yellow = 1'h0;
    end
  end
endmodule
